[package]
name = "nyx"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
glam = { version = "0.26.0", features = ["bytemuck", "serde"] }
serde = { version = "1.0.197", features = ["derive"] }
