[package]
name = "nyx"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.26.0", features = ["bytemuck", "serde"] }
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
