[package]
name = "hypnos"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
bincode = "1.3.3"
crossbeam-channel = "0.5.12"
glam = "0.26"
nyx = { version = "0.1.0", path = "../nyx" }
